# Report code coverage to Codecov.
name: Report coverage

on: [push, workflow_dispatch]

jobs:

  coverage:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            python: ['3.10', '3.13']

    steps:
      - name: Check out code.
        uses: actions/checkout@v4

      - name: Set up Python.
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python }}

      - name: Install project.
        run:  pip install --editable .[dev]

      - name: Measure code coverage.
        run:  pytest --cov --cov-report xml

      - name: Upload coverage report.
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
